consumes:
- application/json
definitions:
  Couchbasecluster:
    description: A CouchbaseCluster (default view)
    example:
      cluster_id: FooAWSStack123
      initial_node_ip_addr_or_hostname: 10.1.1.1
      is_initial_node: true
    properties:
      cluster_id:
        description: The cluster id
        example: FooAWSStack123
        type: string
      initial_node_ip_addr_or_hostname:
        description: The initial node ip address or host that can be used to join
          cluster
        example: 10.1.1.1
        type: string
      is_initial_node:
        description: Whether the node_ip_addr_or_hostname passed in the request represents
          the initial node in the cluster
        example: true
        type: boolean
    required:
    - cluster_id
    - initial_node_ip_addr_or_hostname
    - is_initial_node
    title: 'Mediatype identifier: application/vnd.couchbasecluster+json; view=default'
    type: object
  CreateOrJoinClusterPayload:
    example:
      cluster_id: 3gj
      node_ip_addr_or_hostname: "5"
    properties:
      cluster_id:
        example: 3gj
        minLength: 1
        type: string
      node_ip_addr_or_hostname:
        example: "5"
        minLength: 1
        type: string
    required:
    - cluster_id
    - node_ip_addr_or_hostname
    title: CreateOrJoinClusterPayload
    type: object
  GetStatusClusterPayload:
    example:
      cluster_id: 3gj
      node_ip_addr_or_hostname: "5"
    properties:
      cluster_id:
        example: 3gj
        minLength: 1
        type: string
      node_ip_addr_or_hostname:
        example: "5"
        minLength: 1
        type: string
    required:
    - cluster_id
    title: GetStatusClusterPayload
    type: object
host: localhost:8080
info:
  description: REST API to enable bootstrapping Couchbase Server clusters
  title: REST API to enable bootstrapping Couchbase Server clusters
  version: ""
paths:
  /cluster:
    post:
      description: Create a new Couchbase Cluster
      operationId: cluster#create_or_join
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/CreateOrJoinClusterPayload'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Couchbasecluster'
      schemes:
      - http
      - https
      summary: create_or_join cluster
      tags:
      - cluster
  /cluster/{cluster_id}:
    get:
      description: Get Couchbase Cluster by ID
      operationId: cluster#status
      parameters:
      - description: Cluster ID
        in: path
        name: cluster_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Couchbasecluster'
      schemes:
      - http
      - https
      summary: status cluster
      tags:
      - cluster
  /cluster/get_status:
    post:
      description: Get Couchbase Cluster by ID.  Works around URL encoding issues
        seen in GET with :cluster_id URL param
      operationId: cluster#get_status
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/GetStatusClusterPayload'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Couchbasecluster'
      schemes:
      - http
      - https
      summary: get_status cluster
      tags:
      - cluster
produces:
- application/json
responses:
  OK:
    description: OK
    schema:
      $ref: '#/definitions/Couchbasecluster'
schemes:
- http
- https
swagger: "2.0"
